name: deploy-on-vercel

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      java_version:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - name: Install Vercel CLI
        run: bun install --global vercel
      - name: Pull Vercel environment info
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Build JS
        run: sbt fullLinkJS
      - run: bun install
      - run: bun run build
      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel deploy --target=${{ inputs.environment }} dist --token=${{ secrets.VERCEL_TOKEN }} --yes
