name: main

on:
  push:
    branches: ["main"]

env:
  JAVA_VERSION: '24'

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      code: ${{ steps.filter.outputs.code }}
      workflows: ${{ steps.filter.outputs.workflows }}
      yml: ${{ steps.filter.outputs.yml }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - "src/**"
              - "project/**"
              - "*.js"
              - "*.ts"
              - "*.sbt"
              - "*.lock"
              - "*.conf"
              - .bun-version
              - index.html
              - package.json
              - ".github/workflows/main.yml"
            workflows:
              - ".github/**/*.yml"
            yml:
              - "**.yml"
              - "**.yaml"

  lint:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: sbt
      - name: Install scalafmt
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: scalameta/scalafmt
          tag: v3.9.5
      - name: Check formatting
        run: scalafmt --check src/main/scala

  build:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Build JS
        run: sbt fullLinkJS
      - name: Check generated JS file exists
        run: |
          if [ ! -f target/scala-3.7.2/chronotes-opt/main.js ]; then
            echo "generated JS file not found"
            exit 1
          fi
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - run: bun install
      - run: bun run build

  deploy-staging:
    needs: [changes, lint, build]
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: macos-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy
        uses: ./.github/actions/deploy-on-vercel
        with:
          environment: preview
          java_version: ${{ env.JAVA_VERSION }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}

  deploy-prod:
    needs: [changes, deploy-staging]
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: macos-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy
        uses: ./.github/actions/deploy-on-vercel
        with:
          environment: production
          java_version: ${{ env.JAVA_VERSION }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
