name: pr

on:
  pull_request:

env:
  JAVA_VERSION: '24'

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      code: ${{ steps.filter.outputs.code }}
      workflows: ${{ steps.filter.outputs.workflows }}
      yml: ${{ steps.filter.outputs.yml }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - "src/**"
              - "project/**"
              - "*.js"
              - "*.ts"
              - "*.sbt"
              - "*.lock"
              - "*.conf"
              - .bun-version
              - index.html
              - package.json
              - ".github/workflows/pr.yml"
            workflows:
              - ".github/**/*.yml"
            yml:
              - "**.yml"
              - "**.yaml"

  lint:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: sbt
      - name: Install scalafmt
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: scalameta/scalafmt
          tag: v3.9.5
      - name: Check formatting
        run: scalafmt --check src/main/scala

  build:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Build JS
        run: sbt fullLinkJS
      - name: Check generated JS file exists
        run: |
          if [ ! -f target/scala-3.7.2/chronotes-opt/main.js ]; then
            echo "generated JS file not found"
            exit 1
          fi
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - run: bun install
      - run: bun run build

  check-preview:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      preview: ${{ steps.check_commit.outputs.preview }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check if preview should run
        id: check_commit
        run: |
          # Get the commit message from the current HEAD (PR head)
          commit_message="$(git log -1 --pretty=%B)"
          echo "Commit message: $commit_message"
          if echo "$commit_message" | grep -q "\[no-preview\]"; then
            echo "Found [no-preview] - will skip preview"
            echo "preview=false" >> "$GITHUB_OUTPUT"
          else
            echo "preview=true" >> "$GITHUB_OUTPUT"
          fi

  preview:
    needs: check-preview
    if: ${{ needs.check-preview.outputs.preview == 'true' }}
    runs-on: macos-latest
    environment: preview
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy-on-vercel
        with:
          environment: preview
          java_version: ${{ env.JAVA_VERSION }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
