name: preview
on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy-on-vercel.yml
    with:
      environment: preview
      java_version: '24'
    secrets: inherit
