name: preview
on:
  push:
    branches-ignore:
      - main

env:
  JAVA_VERSION: '24'

jobs:
  deploy:
    runs-on: macos-latest
    uses: ./.github/workflows/deploy-on-vercel.yml
    with:
      environment: preview
      java_version: ${{ env.JAVA_VERSION }}
    secrets: inherit
