name: preview

on:
  pull_request:

env:
  JAVA_VERSION: '24'

jobs:
  deploy:
    runs-on: macos-latest
    environment: preview
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy-on-vercel
        with:
          environment: preview
          java_version: ${{ env.JAVA_VERSION }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
