name: preview
on:
  push:
    branches-ignore:
      - main

env:
  JAVA_VERSION: '24'

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy-on-vercel
        with:
          environment: preview
          java_version: ${{ env.JAVA_VERSION }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_token: ${{ secrets.SOME_TOKEN }}
