name: release

on:
  push:
    branches:
      - main

env:
  JAVA_VERSION: '24'

jobs:
  deploy-staging:
    runs-on: macos-latest
    concurrency:
      group: deploy-staging
    environment: staging
    uses: ./.github/workflows/deploy-on-vercel.yml
    with:
      environment: preview
      java_version: ${{ env.JAVA_VERSION }}
    secrets: inherit

  deploy-prod:
    runs-on: macos-latest
    needs: [deploy-staging]
    concurrency:
      group: deploy-prod
    environment: prod
    uses: ./.github/workflows/deploy-on-vercel.yml
    with:
      environment: production
      java_version: ${{ env.JAVA_VERSION }}
    secrets: inherit
