name: release

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    concurrency:
      group: deploy-staging
    environment: staging
    uses: ./.github/workflows/deploy-on-vercel.yml
    with:
      environment: preview
      java_version: '24'
    secrets: inherit

  deploy-prod:
    needs: [deploy-staging]
    concurrency:
      group: deploy-prod
    environment: prod
    uses: ./.github/workflows/deploy-on-vercel.yml
    with:
      environment: production
      java_version: '24'
    secrets: inherit
